<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addNumJS</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgaW5wdXQgPSBuZXcgSURhdGFNYXAoKTsNCmlucHV0LnB1dCgibnVtMSIsIG5ldyBJ
RGF0YU1hcChwaXBlbGluZSkuZ2V0QXNTdHJpbmcoImEiKSk7DQppbnB1dC5wdXQoIm51bTIiLCBu
ZXcgSURhdGFNYXAocGlwZWxpbmUpLmdldEFzU3RyaW5nKCJiIikpOw0KdHJ5IHsNCglJRGF0YSBk
b0ludm9rZSA9IFNlcnZpY2UuZG9JbnZva2UoTlNOYW1lLmNyZWF0ZSgicHViLm1hdGg6YWRkSW50
cyIpLCBpbnB1dC5nZXRJRGF0YSgpKTsNCgluZXcgSURhdGFNYXAocGlwZWxpbmUpLnB1dCgiYyIs
IG5ldyBJRGF0YU1hcChkb0ludm9rZSkuZ2V0QXNTdHJpbmcoInZhbHVlIikpOw0KfSBjYXRjaCAo
RXhjZXB0aW9uIGUpIHsNCgkvLyBUT0RPIEF1dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrDQoJZS5w
cmludFN0YWNrVHJhY2UoKTsNCn0=</value>
</Values>
